# Uncomment the below/add additional env variables to add them to the lambda
# === ENVIRONMENT_VARIABLES ===
environment_variables:
    LOG_LEVEL: debug
    OUTPUT_REGION: us-east-1
    OUTPUT_KINESIS: sfr-db-update-development